name: Build App (Windows)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m venv .venv
          .venv\Scripts\activate
          pip install --upgrade pip
          pip install .
          pip install pyinstaller
          pip install certifi
      - name: Build executable
        run: |
          .venv\Scripts\activate
          pyinstaller run_gui.spec
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-dist
          path: dist/
