name: Build App (macOS)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install .
          pip install pyinstaller
          pip install certifi
      - name: Build executable
        run: |
          source .venv/bin/activate
          pyinstaller run_gui.spec
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-dist
          path: dist/
